runs:
  using: "composite"

  steps:
  - name: CMake configure
    shell: bash
    run: >-
      cmake -B ${{ inputs.build_dir }} -S ${{ github.workspace }}

  - name: CMake build
    shell: bash
    run: cmake --build ${{ inputs.build_dir }}