runs:
  using: "composite"

  steps:
  - name: CMake configure
    shell: bash
    run: >-
      cmake -B build_dir -S ${{ github.workspace }}

  - name: CMake build
    shell: bash
    run: cmake --build build_dir