name: 'The Cmake Composite Action'
description: 'A composite action for CMake configure, build, and test.'

inputs:
  build_dir:
    description: 'The build directory'
    required: true


runs:
  using: "composite"

  steps:
  - name: CMake Configure
    shell: bash
    run: >-
      cmake -B ${{ inputs.build_dir }} -S ${{ github.workspace }}

  - name: CMake Build
    shell: bash
    run: cmake --build ${{ inputs.build_dir }}
    
  - name: Cmake Test
    shell: bash
    run: ctest --test-dir ${{ inputs.build_dir }}