name: Test MPI with CMake

on: [push, pull_request]

jobs:
  test-mpi:
    runs-on: macos-latest
    name: Test MPI detection with CMake
    timeout-minutes: 60

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Homebrew
      run: brew update

    - name: Install MPI
      run: brew install open-mpi

    - name: Cmake (configure, build)
      uses: ./.github/actions/composite-cmake

    - name: Run the executable
      run: mpirun -np 2 ./test_mpi
