name: Test MPI with CMake

on: [push, pull_request]

jobs:
  test-mpi:
    runs-on: macos-latest
    name: Test MPI detection with CMake
    timeout-minutes: 60

    strategy:
      matrix:
        cc: [clang, gcc-14]
    
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CC: ${{ matrix.cc }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Homebrew
      run: brew update

    - name: Install MPI
      run: brew install open-mpi

    - name: Cmake (configure, build)
      uses: ./.github/actions/composite-cmake
      with:
        build_dir: ${{ runner.temp }}
